### ISSUE TITLE
Page break errors

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#12]
This is to document a known bug in the xml creation.

The confirming example is D545.   Here, the verse (`<S> abhyodhiH  etc.`)  starts on page 100,
but make_xml.py generates `<info n="L=545: S,D,F 1.101"/>`,   
which should be `<info n="L=545: S,D,F 1.100"/>`

This happens because a footnote to D544  (`<F>544`) has a page break `[Seite1.101]`  and the `<F>`
occurs sequentially before the `<S> abhyodhiH  etc.`

Some way is needed to correct this.

**Comment by thomasincambodia** [comment]
@funderburkjim 

would  \<pb n=1.101\\\> help?

**Comment by Andhrabharati** [comment]
I would suggest moving all F.s immediately after the D.s belonging to a set of S.s; thus every piece of data belonging to resp. S no.(s)

**After all we are not going to print a book, but just making a digital text for cross-linking.**

BTW @funderburkjim, there are some G.(s) [Greek text blocks] under some verses, and @thomasincambodia suggested me to take your consent for making those texts.

Pl. have a look at #16, where the discussion to place and give your opinion.

**Comment by funderburkjim** [comment]
> moving all F.s immediately after the D.s belonging to a set of S.s; thus every piece of data belonging to resp. S no.(s) will be together as a single block.

This is the way @thomasincambodia is handling footnotes.   Similarly for 'V' and 'W' sections, which are
'corrections/additions'.  Everything for a 'saying' is together.  In the xml form derived from Thomas digitization,  these are called 'entry' elements,  and an entry has all the children (sections) belonging to the
verse.  (see boesp.dtd, which is used to validate the boesp.xml).

**Comment by funderburkjim** [comment]
> would changing [Seite1.101] into `<pb n=1.101\>` help?

@thomasincambodia 

I don't think so.   Just keep `[Seite1.101]` form for now.

**Comment by Andhrabharati** [comment]
is it a time to close this issue?
