### ISSUE TITLE
the joy of git diff

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#14]
@thomasincambodia  -- 
I just finished doing some revisions to the slp1 version of sanskrit that Sampada will be working with.

I thought you should see one of the advantages of line preservation (when possible).

These revisions were fairly numerous 500+.  
They can be reviewed via this Github link.  [in general, the history of a file is available in such views]

https://github.com/funderburkjim/boesp-prep-sam/commit/f882e13841033587ea9e6301f17640a5859606b9

Reiview of this nicely formatted diff allowed me to review to confirm that what I intended to do was done.

Moral of story is:  Git has good support for reviewing history of changes to a file.  This support is based
on changes in lines in the file.  This support is greatest when a given commit contains a relatively focused
set of changes.  

You can see the history of boesp-1_ansi.txt at this link:
https://github.com/funderburkjim/boesp-prep/commits/main/step0/boesp-1_ansi.txt

And you can see the 'diff' display at any commit.

**Comment by funderburkjim** [comment]
One drawback of these displays of boesp-1_ansi.txt that I notice is that the displays seem to assume
utf-8 encoding.  So you don't see extended ascii characters in this file properly, since this file uses
cp1252 encoding for extended ascii.  There may be some workaround for this problem, I'm not sure.

![image](https://user-images.githubusercontent.com/6393033/132584632-47e2eb53-3e98-43d5-b2de-a7ba3c5e87c8.png)

**Comment by Andhrabharati** [comment]
@funderburkjim 

pl. have a look at

https://github.com/microsoft/vscode/issues/23322

and

https://github.com/aadsm/jschardet#supported-charsets

with some setting to enable autodetect file encoding windows 1252 diff seems to be alright.

**Comment by thomasincambodia** [comment]
@funderburkjim 

there is no difficulty in  reading a German text without proper umlauts. It happens quite frequently in English rendering of German words. But perhaps @Andhrabharati's suggestion solves the problem.

**Comment by drdhaval2785** [comment]
I am not sure whether all concerned know it or not. There is a `--word-diff` option to `git diff`. 

When seeing diff and the line changed is long, I find it very usefull to find out changed item precisely.

`git diff --word-diff commit1 commit2` is the command to execute in terminal.

**Comment by funderburkjim** [comment]
@Andhrabharati   I did look at the references, but did not see immediately how to use.  However,  since Thomas not bothered
by the umlauts, will not worry about this now.   My first processing step is to convert from boesp-1_ansi.txt (cp1252 encoding) to
boesp-1_utf8.txt (utf-8 encoding),  and all the subsequent derived files are utf-8 encoding.
