### ISSUE TITLE
F section problems

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#22]
@thomasincambodia 

A few problems with Footnotes.  All look easy to correct.  Here are suggestions.
```

typos
 F problem ['<S>', '<D682>', '<F>282)']   F282 -> 682
 F problem ['<S>', '<D2121>', '<F>1121)'] F1121->2121
 F problem ['<S>', '<D2795>', '<D2796>', '<F>2765.96)']  F2765 -> 2795
 F problem ['<S>', '<D6846>', '<F>8646)']  F8646 -> 6846
 F problem ['<HS>', '<S>', '<D6847>', '<F>8647)'] F8647 -> 6847
 F problem ['<S>', '<D6968>', '<F>6868)'] F6868 -> 6968

 F677 needs to be moved up after D677
F problem ['<S>', '<F>677)', '<D678>', '<F>678)']

 next more complex
 F problem ['<S>', '<F>5281)', '<S>', '<D5282>', '<F>5282)']

<S> yadyapi bhvAtaraH kvuddhA bhAryA ca· 
kAraNAntare | svabhAvataste prIyante· 
netraH prIyate janaH ||· 
 
<F>5281) SUBHA1SH. 296. ²b. {#rAsabho#}· << REMOVE DUPLICATE
die Hdschr.· 
 
<S> yadyapi bhvAtaraH kvuddhA bhAryA ca· << REMOVE DUPLICATE
kAraNAntare | svabhAvataste prIyante· 
netraH prIyate janaH ||· 
 
<D5282><A4832> Wenn Brüder oder die· 
Gattin uns auch zürnen aus irgend einem· 
Grunde, so lieben sie uns doch in Folge· 
der natürlichen Verhältnisse; die andern· 
Menschen aber lieben uns nicht.· 



``

**Comment by funderburkjim** [comment]
A similar check of compatibility between V1 numbers and D numbers  finds no problems;
similarly with V2 and V3  (i.e. all the V1, V2,V3 notes have been placed in the right D-group. 👍

**Comment by thomasincambodia** [comment]
corrected and git pushed

**Comment by funderburkjim** [comment]
## Reposition H
@thomasincambodia 

There are three '<H>' sections.
In First one `<H>Räthsel.· ` needs to be place AFTER `<F>1427`.
Similarly, Second one `<H>Auflösung.`, should be placed AFTER `<F>1428`

The third one `<H>Nachträge.` is properly placed.

**Comment by funderburkjim** [comment]
@thomasincambodia   Are you going to do the previous two changes to boesp.all_ansi.txt?  or should I?

**Comment by thomasincambodia** [comment]
@funderburkjim 
I have made those changes, but don't think tehre is a need to upload boesp.all_ansi.txt anew if you are doing it on your side.

**Comment by funderburkjim** [comment]
OK.  I can live with that.

**Comment by funderburkjim** [comment]
BTW, did you make your changes in the file 'boesp-prep/step0/boesp.all_ansi.txt'  or did you make the changes in another file (e.g. a copy of boesp.all_ansi.txt)?
