### ISSUE TITLE
AS checking

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#23]
I think the next item for me to check will be the AS coding in literary source references.

## identifying literary source
It seems that the literary sources are identified as  'words' that
* are not tags 
* are not in `<S>` sections
* start with a capital letter
* contain only capital letters and digits.

@thomasincambodia   Do you confirm this is the way to identify ls sources?  Have I missed any details?
For instance, should there always be an ending period in these ls identifiers?

**Comment by funderburkjim** [comment]
## first frequency count
@thomasincambodia 
[this file](https://gist.github.com/funderburkjim/19b275ed4d6a810d1dd7f55f1f68bcca) shows result of first attempt at identifying LS (AS) items in boesp-all.  There is also an attempt at matching to pwg LS abbreviations.

Probable next step is to make changes to unite obvious spelling variants  (e.g. BENFET -> BENFEY).

**Comment by thomasincambodia** [comment]
@funderburkjim 
the "obvious spelling varints" would be most likely typo

**Comment by Andhrabharati** [comment]
And why leave the Foreword/Preface pages?

Having them all typed would make it a FULL digitisation!!
