### ISSUE TITLE
superscript-2 implies italic

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#24]
@thomasincambodia   I think you mentioned that `²a.` in boesp.all  IMPLIES that the 'a' is italic.

I see several cases like `{%²c. ²d. %}`  (from F>83).

I think these should be changed to `²c. ²d. `,  since the italic markup via `{% %}`  is redundant.

Agree?

**Comment by thomasincambodia** [comment]
agreed

**Comment by Andhrabharati** [comment]
issue closable?
