### ISSUE TITLE
Reformat <S> lines

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#28]
Work is done in preparation  for reformatting the `<S>` lines of boesp.
This work based on boesp.all_ansi,  with volumes 1-3.

Example:
```
OLD:
<S> aMzo 'pi duSTadiSTAnAM pareSAM· 
syAdvinAzakRt | vAlalezo 'pi vyAghrANAM· 
patsyAjjIvitahAnaye ||· 
NEW:
<S>
aMzo 'pi duSTadiSTAnAM pareSAM syAdvinAzakRt |·
vAlalezo 'pi vyAghrANAM patsyAjjIvitahAnaye ||· 
```

Also the 200 or so verses with 'long' lines are reformatted to agree more closely with the 
printed text.
First Example, at saying D75:
```
OLD:
<S> agrAhyaM hRdayaM tathaiva vadanaM yaddarpaNAntargataM @ bhAvaH parvatasUkSmamArgaviSamaH strINAM na vijJayate |· 
cittaM puSkarapattratoyataralaM vidvadbhirAzaMsitaM @ nArI nAma viSAGkarairiva latA doSaiH samaM vardhitA ||· 
NEW:
<S> agrAhyaM hRdayaM tathaiva vadanaM yaddarpaNAntargataM· 
bhAvaH parvatasUkSmamArgaviSamaH strINAM na vijJayate |· 
cittaM puSkarapattratoyataralaM vidvadbhirAzaMsitaM. 
nArI nAma viSAGkarairiva latA doSaiH samaM vardhitA ||· 
```

Note that only preparation for making these changes has been done.
The changes have not yet been installed within boesp.all_ansi.txt.
When Thomas installs the new Volume 4 verses (but before he installs the volume 4 footnotes and corrections), then we will consider whether it is appropriate to install the prepared changes.

**Comment by funderburkjim** [comment]
@thomasincambodia   This preparatory work has been pushed to Github.
So, when you're ready to push your boesp.all_ansi.txt additions for Volume 4 verses, be sure
to do a 'git pull'.  Then, the usual git add, git commit -m "xxx", and git push.

**Comment by thomasincambodia** [comment]
@funderburkjim 
Noted.

Here some preliminary remarks on Boesp4.2(B.)_ansi.txt file.

This file contains the second part (pp. 217-249) of "Zweiter Nachtrag zu meinen Indischen Sprüchen" published in Mélanges Asiatiques [...],  Vol. 8/1-2 St. Petersburg 1877.

It consists of: 
--1) 252 numbered additions (7614 to 7865)  of Sanskrit Sprüche  found in subha1s2ita ratna1kara, Bombay 1872,  
--2) 13 additional references to Th. Aufrecht, Ueber die Paddhati von S4a1rn3gadhara, Zeitschrift der deutschen Morgenländischen Gesellschaft, Vol 27-1, 1873.  
--3) 4  references to Sprüche numbers in Boesp1-3,
variants(?) presumably also taken from subha1s2ita ratna1kara ( I have not yet checked).

All the three varieties of verses are listed alphabetically.

1) is marked <S> followed by an empty <D> marker, as there are no German translations, followed by <F> footnotes containing sources and variants

2) Aufrecht's contributions are preliminarily marked <h3>

3) the references are preliminarily marked <h4>

I have no idea so far how to integrate 2) and 3) into Boesp

**Comment by thomasincambodia** [comment]
pushed boesp4.2(B.)_ansi.txt

**Comment by funderburkjim** [comment]
Pushed S-normalization changes into boesp.all_ansi.txt.
The changes can be reviewed with
```
git diff 3866288 bd09c68  -- boesp.all_ansi.txt

# The two numbers are derived from 'git log',
# the first one is the abbreviated hash of a recent commit
# and the second is the abbreviated hash of the  commit I just made.

```
This shows the first 'page' of differences, with a ':' at bottom of page.  Typing 'space' will show the next page of differences.   To quit the display, type 'q'.

You could see send the entire diff to a text file  by
```
git diff 3866288 bd09c68  -- boesp.all_ansi.txt > tempdiff.txt
Note that files whose name starts with 'temp' are not tracked by git (e.g.  will not be pushed).  This is because of the way the '.gitignore' file is set up for this boesp-prep repository.

```

The changes are also in the file changes/change_10.txt.

Maybe too much detail.

**Comment by funderburkjim** [comment]
## corrections for duplicate verses.

The first line of verses were compared, and verses with same first line examined.
About 50 such duplicate groups.

Each of these was examined in light of the printed text.
A summary of the examination is in [checkdup_edit.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step2/check/checkdup_edit.txt).

Of these, about half were found to be in agreement with the text -- e.g., verse 418 and 419 do have the same first line, but the second line differs.  There were no 'fully' duplicate verses.  These cases generated no changes (although a small number of typos were noticed and changed).

For the other half (like 118 and 119),  the digitization was in error. Usually the error was that one of the verses needed to be rewritten - this was done by typing the HK version of the printed Devanagari text.

The changes can be examined by 
* git diff bd09c68  e54aa87 -- step0/boesp.all_ansi.txt
   * Note the 'step0/' is needed if the current direction is boesp-prep.  
* by clicking the e54aa87 link above, and then clicking 'Load diff' -- 
* Looking at file [step0/changes/change_11.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step0/changes/change_11.txt)  (or looking locally at this file).

**Comment by funderburkjim** [comment]
I am now currently done with boesp.all_ansi.txt, which you should pull.

I'll look at Boesp4.2(B.)_ansi.txt next, in light of your comments.

**Comment by funderburkjim** [comment]
## Rename
I renamed 'Boesp4.2(B.)_ansi.txt' to boesp4.2B_ansi.txt.
Reason: the parentheses are awkward in file names.

**Comment by funderburkjim** [comment]
Several editing steps makde to boesp4.2B.

1) use ° instead of º  (degree sign rather than masculine ordinal indicator)
  About 30 replacements.
2) `<eng>` replacements.
  * 35 in Devanagari text in Footnotes
  * 5 in German text in Footnotes
  * 7 in `<S>` verse,  move to Footnote  (7678, 7724, 7752)
     * in 7725, also remove `<F>7614) KALPATARU ...`
3) AS spelling changes
   * BHA1MINI1VHA1SA : 1
   * G4INADHARMAVIVEKA : 1
   * KUVALAJA1NANDA : 2
   * NAISH : 1
   * PAN4CA1JUDHAPRAPAN4CABHA1N2A : 2
   * PAN4CA1JUDHAPRAPAN4CABHA1NA : 1
   * PRASAN3GARATNAVALI1 : 1
   * RA1DHA1KR2SHN2ASAM3VA1DA : 2
   * RATNA1V : 2
   * VAIDJAG4I1VANA : 1
   * VIDVADBHU1SHAN2A : 1
   * VIT2HORA1AN2N2A1 : 1

**Comment by funderburkjim** [comment]
I think boesp4.2B_ansi.txt can be inserted at the end of boesp.all_ansi.txt
Then, remove the first three lines of the inserted boesp4.2B_ansi.txt, namely
```
<!--This_File_is_D:\BOESP\BOESP4.2(B.)_ANSI.TXT,_Last_update_11/06/21--> 
 
<h2>B.</h2> 
```

I've checked that this combination looks fine in terms of groups.

We also will need to put `[Seite4.2-217]` somewhere, but not sure exactly where yet.

**Comment by funderburkjim** [comment]
On the way to adding dummy `<F>` groups, am finding several missing verses, and misplaced footnotes and additions.  Will likely not finish adding the needed empty `<F>` groups until tomorrow.

**Comment by funderburkjim** [comment]
## empty-F preparation
changes were made to boesp.all_ansi.txt in preparation for adding the empty `<F>` blocks.  

The changes may be reviewed in commit 0d46f23.

A copy of the  utf8-version is in [changes/boesp_13.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step0/changes/boesp_13.txt)

Working notes for the changes are in [changes/change_13.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step0/changes/change_13.txt)

**Comment by funderburkjim** [comment]
## dummy F-groups added.

Dummy F-groups  (of form `<F>X) DUMMY`) are added after the compound F-groups.
e.g. 
```
<F>67.68.69) MBH. 5, 1393. fgg. Der· 
letzte {|S4loka|} auch 1411, ²b. 1412,· 
²a, wo aber in ²a. {#nityaM santaH#} st.· 
{#evameva#} gelesen wird.· 
 
<F>67) DUMMY· 
 
<F>68) DUMMY· 
 
<F>69) DUMMY· 
```

The resulting version of boesp.all_ansi.txt may be seen at commit 262fee2.

A copy of the utf-8 version is also available at [changes/boesp_14.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step0/changes/boesp_14.txt).

**Comment by funderburkjim** [comment]
@thomasincambodia   boesp.all_ansi.txt now ready for you to 
1) add the verses from 4.2B
2) insert the `<F4>` and `<F5>` footnotes.

**Comment by thomasincambodia** [comment]
@funderburkjim 
<F4.1C>-- S. 539, Z. 4. Lies «vorangehenden» st. «folgenden».</F4>
<F4.1C>-- S. 624, Z. 9 v. u. Lies 777 st. 776.</F4>
<F4.1C>-- S. 633, Spr. 2152. Lies drei Mal BAHUD. st. NI1TIS4.</F4>
<F4.1C>-- S. 639, Z. 2. Lies 3187 st. 3189 und streiche in Folge dessen {%c. d.%} u. s. w.</F4>
<F4.1C>-- S. 641, Spr. 3754, Z. 2 lies 11 st. 12.</F4>
<F4.1C>-- S. 642, Spr. 3979, Z. 2. Streiche «in Telugu-Charr.».</F4>
<F4.1C>-- S. 643, Spr. 4116. Füge «GALAN. Varr. 170» hinzu.</F4>
<F4.1C>-- S. 647, Spr. 5589, Z. 2. Lies 20, 38. Am Ende hinzuzufügen: <i>d</i>. {#pAdam#} st. {#padam#}.</F4>
<F4.1C>-- S. 649, Spr. 6528, Z. 3. Lies {#kSIreNAyuSyaº#}. 
--- Zum Schluss bemerke ich noch, dass alle hier mitgetheilten Berichtigungen und Ergänzungen zu den Indischen Sprüchen in den vorangehenden Artikeln schon verwerthet worden sind.</F4>
-----
Above are the doubtful correction cases, which I have also put at the top of boesp.all_ansi.txt.
(End-of-line markers have also to be added to all new lines.)
I finished adding the <F4.1> and <F4.2> but have not changed them to  <F4> <F5>.

I pushed boesp.all_ansi.txt for you to have a look at.

**Comment by funderburkjim** [comment]
Have been working on PWK literary sources.

**Comment by Andhrabharati** [comment]
@funderburkjim,

Both @sanskritisampada and I have completed proof-reading the boesp-1 verses.

You may now do necessary checking and incorporate these into the boesp_all file(s).

**Comment by Andhrabharati** [comment]
Also the Greek portions were finalized by @jmigliori and submitted in various phases, to be inserted at resp. places appropriately.

So, if (and when) you make the full file in Unicode (Devanagari, Roman and Greek), I can go ahead with reading the other portions.

**Comment by Andhrabharati** [comment]
issue closable?
