### ISSUE TITLE
Undigitized V3

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#31]
## undigitized V3

In dealing with `<F4.1C>-- S. 624, Z. 9 v. u. Lies 777 st. 776.· `,  I found that `<V3>776.`  (#29) had not been typed!
I typed it  (changing it to `<V3>777` and put under D777.

Further,  went through entire list of `<V3>` and found numerous others that are not part of current digitization
```
V3 missing:
p. 624:  709 776
p. 631: 1830 1841 1851
p. 632: 2048 2049
p. 634: 2322 2361 
p. 638 3073 
p. 640 3554 
p. 644 4434 is present but wrong. 4531 missing
p. 645 4650 4735 4745 4755 4790 4805 4806 4815
    5211 is digitized but not in print (is part of 5201 ?)  cf.  p.650 (see below)
p. 649 6526 6869 
p. 650 5211 (bottom of page, out of order) ?
```
All of these (20+) need to be digitized.

**Comment by funderburkjim** [comment]
## V1
All V1 are digitized.
One item to examine:
In the digitization, there is `<V1>1019`, but this is not found in print.

**Comment by funderburkjim** [comment]
Next task is to resolve the problems above.  Beginning task.

**Comment by Andhrabharati** [comment]
> ## V1
> 
> All V1 are digitized. One item to examine: In the digitization, there is `<V1>1019`, but this is not found in print.

See this in V1-
; 1019 : page 1.191

**Comment by Andhrabharati** [comment]
Vol.2 has V.s for Spr.103-2219 (of Vol.1), then continued for Vol.2 Spr.s

**Comment by Andhrabharati** [comment]
And so is Vol.3 having V.s pertaining to all the three vol.s

**Comment by funderburkjim** [comment]
> V1 1019

@Andhrabharati  Thanks for tip.  Digitization has mislabeled this as V1, and it should be V2.

**Comment by funderburkjim** [comment]
# When is V2 same as V3 ?

In correcting the V2.160,  noticed that there is also a V3.160 and the two are identical  (confirmed from pdf).

Is this a pattern, such as 'V3 contains V2' ?

**Comment by funderburkjim** [comment]
## correction re extra `<V2>2219`
The duplicate V2.2219 is part of the F2219.

```
OLD:
<F>2219) SUBHA1S2. 208. ²a.· 
{#candanazcArugandhiH#}· 
  
<V2>2219. die Hdschr. ²c. {#kAntivarNaM#}· 
die Hdschr. ²d. {#nobhamAnAM#} die Hdschr.· 
 
<V2>2219. Eine Variante von 2684.· 
[Seite1.435]· 

NEW:
<F>2219) SUBHA1S2. 208. ²a.· 
{#candanazcArugandhiH#}· 
die Hdschr. ²c. {#kAntivarNaM#}· 
die Hdschr. ²d. {#nobhamAnAM#} die Hdschr.· 
[Seite1.435]· 

<V2>2219. Eine Variante von 2684.· 
```

**Comment by funderburkjim** [comment]
The correction task to V1,V2,V3 completed, and boesp.all_ansi.txt and boesp_utf8.txt revised.
A copy is also in changes/boesp_22.txt.
