### ISSUE TITLE
Ordering of F,V sections

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#33]
## Current formatting

An *entry* consists of 
* 0 or more `<HS>` groups (Spruch cross references)
* exactly 1 `<S>` group
* 1 or more `<D>` groups (usually 1, but 2 or more in 159 cases)
  * There are always the same number of D groups as Spruch, but the multiple spruch are written under  1 S group.
*  for each D group, exactly 1 ~S-group~ F-group,  
* 0 or 1 of `<V1>, <V2>, <V3>, <F4.1>, <F4.2>`

## Suggestion
In textual order, the V1, V2, V3, F4.1 and F4.2 sections should appear in that order.
However, the current digitization does not have this ordering. For instance
* `<S>,<D278>,<F>278),<V3>278. ,<V1>278. `
* `<S>,<D349>,<F>349),<F4.2>,<V3>349. `

The suggestion is to move the V and F items so the textual order is preserved.

@thomasincambodia   Do you agree?  If so, I'll do that

**Comment by funderburkjim** [comment]
In the first comment, I forgot to say that there is also exactly 1 F for each D.  That comment now edited.

**Comment by funderburkjim** [comment]
## how many?
Emacs search for `<\(V\|F4\).*<\(V\|F4\)`   in [checkgroup.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step2/check/checkgroup.txt) finds 190 matches.  
For instance 
* `<S>,<D11>,<F>11),<F4.2>,<F4.1>`    (F4.1, F4.2 misordered)
* `<HS>,<S>,<D90>,<F>90),<F4.2>,<V3>90. ` (V3, F4.2 misordered)
* `<S>,<D160>,<F>160),<V2>160. ,<V3>160. ,<F4.1>`  ordering correct

So 190 looks to be the number of Spruch to examine in the digitization.

**Comment by thomasincambodia** [comment]
> ## Current formatting
> An _entry_ consists of
> 
> * 0 or more `<HS>` groups (Spruch cross references)
> * exactly 1 `<S>` group
> * 1 or more `<D>` groups (usually 1, but 2 or more in 159 cases)
>   
>   * There are always the same number of D groups as Spruch, but the multiple spruch are written under  1 S group.
> * for each D group, exactly 1 ~S-group~ F-group,
> * 0 or 1 of `<V1>, <V2>, <V3>, <F4.1>, <F4.2>`
> 
> ## Suggestion
> In textual order, the V1, V2, V3, F4.1 and F4.2 sections should appear in that order. However, the current digitization does not have this ordering. For instance
> 
> * `<S>,<D278>,<F>278),<V3>278. ,<V1>278. `
> * `<S>,<D349>,<F>349),<F4.2>,<V3>349. `
> 
> The suggestion is to move the V and F items so the textual order is preserved.
> 
> @thomasincambodia Do you agree? If so, I'll do that

of course, go ahead

**Comment by funderburkjim** [comment]
This reordering work done.
See [this diff](https://github.com/funderburkjim/boesp-prep/commit/a3be03d2f1b726c13ad250a9107c3dc7591eef78).
