### ISSUE TITLE
F4.1 -> V4, F4.2 -> V5 ?

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#37]
@thomasincambodia 
Should the F4.1 and F4.2 section names be changed to V4, V5?

Reason - These are 'really' corrections/additions to various of the verses in volumes 1-3, which happen to be
printed in the two documents currently called 'boesp4-1.pdf' and 'boesp4-2.pdf'. 

The footnotes for the extra verses (D>7613) are marked as such (e.g. `<F n="7614">`)

So V (Verbesserungen) seems better than F (Fussnote).

If we agree on V rather than F, then we have a choice of V-what?  Could be V4.1 and V4.2,  but the
simpler V4, V5 seems slightly preferable to me.

And if we agree on V4 and V5, then better names for the two extra pdfs would be boesp4.pdf and boesp5.pdf.

**Comment by thomasincambodia** [comment]
Agree with all of your proposals.

**Comment by thomasincambodia** [comment]
I had a look at  boesp_utf8.xml and boesp.dtd.

is boesp.dtd complete and supposed to be working in Oxygen?

I have some problems with including <HS> in the following <entry> (why not the previous?) because 
they are independent, though abbreviated, entries,
but have to admit that I do not know how to handle them

**Comment by funderburkjim** [comment]
Also change page-break references similarly:
Example `<pb n="4.1-660"/>` -> `<pb n="4.660"/>`  (8 instances)
Similarly
`<pb n="4.2-206"/>` -> `<pb n="5.206"/>`  (44 instances)

**Comment by funderburkjim** [comment]
It is also necessary to change boesp.dtd,  since now the F4.1 and F4.2 elements are called V4 and V5.

**Comment by funderburkjim** [comment]
These changes now made. About 2200+ lines changed in boesp_utf8.xml.  
See the commit or [changes_03.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step0/changesxml/changes_03.txt) for details.
