### ISSUE TITLE
HS entries

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#39]
Discussion with @thomasincambodia  regarding [this comment](https://github.com/funderburkjim/boesp-prep/issues/37#issuecomment-997143509), leads to the idea that the HS groups should be moved 
* out of their  position as subgroups within normal entries 
* and into separate entries.

**Comment by funderburkjim** [comment]
This has now been done. See [step3a](https://github.com/funderburkjim/boesp-prep/tree/main/step3a).
This picture shows how the first entry with an HS (left) is modified.
Since there is just one HS group, the modification adds one entry containing that HS  (L=12.1) and
removes the HS group from L=12.s

![image](https://user-images.githubusercontent.com/6393033/147307538-577cca11-c627-4b81-8503-df8a2628c124.png)

**Comment by funderburkjim** [comment]
## dtd revised.

boesp.dtd requires a slight adjustment, since there are now 2 types of entries.
See [boesp.dtd](https://github.com/funderburkjim/boesp-prep/commit/943d0af41e5326e8e4b65d7994a30e98b5dad446)

**Comment by funderburkjim** [comment]
## page revision to do later.

In the above construction, the value of the 'page' attribute of the 'info' element of a new HS group is
simply copied from that of its former parent entry.  However, this is sometimes wrong.
For instance consider saying 72:

![image](https://user-images.githubusercontent.com/6393033/147308067-4a014774-983b-4527-bcb4-2ce4350877ae.png)

The revised xml file shows:
```
<entry>
<info L="71.1" page="1.13" gtypes="HS"/>
<HS>
<s>agninprApya</s> s. Spruch 63.
</HS>
</entry>

<entry>
<info L="71.2" page="1.13" gtypes="HS"/>
<HS>
<s>agneH zeSam</s> s. Spruch <s>atyAdaraparaH</s>. <pb n="1.14"/>
</HS>
</entry>

<entry>
<info L="72" page="1.13" gtypes="S,D,F"/>     <<< page should be 1.14
<S>
agnau prAstaM tu puruSaM karmAnveti svayaMkRtam |
tasmAttu puruSo yatnAddharmaM saMcinuyAcchanaiH ||
```

In this case, the original L=72 should have its page attribute value changed from "1.13" to "1.14".

This page revision remains to be done.

**Comment by funderburkjim** [comment]
@thomasincambodia   Any alterations needed in this handling of the HS ?

**Comment by Andhrabharati** [comment]
> Discussion with @thomasincambodia regarding [this comment](https://github.com/funderburkjim/boesp-prep/issues/37#issuecomment-997143509), leads to the idea that the HS groups should be moved
> 
>     * out of their  position as subgroups within normal entries
> 
>     * and into separate entries.

@funderburkjim

The 13 no.s of `<h3>` & 4 no. of `<h4>` candidates are more like the <HS> candidates, and deserve to be treated in the same way.
They are presently put inside the `<F>` tag, which is not correct.

**Comment by funderburkjim** [comment]
I agree that we can move both h3 and h4 into new 'HS' entries, even though the references (at least for h3) are to Aufrecht, rather than to other Spruch. 
  These all occur in the '5th' volume  (Melanges Asiatique, Tome viii, 1877.)

Will attend to that next.

**Comment by funderburkjim** [comment]
@Andhrabharati  vol. 3 verses prepared for you.  See #49.

**Comment by funderburkjim** [comment]
Commit 73b4355 moves the h3,h4 elements into separate HS entries.
See [step4e directory](https://github.com/funderburkjim/boesp-prep/tree/main/step4e) for details.

**Comment by funderburkjim** [comment]
@thomasincambodia  Any comments on this repositioning of h3/h4 elements?

**Comment by thomasincambodia** [comment]
whereas \<h4\> elements are cross references to other Spr. and therefore comparable to \<HS\> elements,
\<h3\> elements  are not.

They are Spr. taken from Aufrecht and alphabetically ordered in the numbered list of additional entries in the 2nd additions and corrections in  boesp5. I think these truncated entries  should be  completed by copying them from the original article (no big deal as there are only 13 of them)   and then given their  positional numbering  plus, say, 'a'. 
The first occurrence of an Aufrecht Spr. would then be numbered _7668a_ i.e. \<info L="7668a" [etc.] \/\>

**Comment by funderburkjim** [comment]
@thomasincambodia   Here is a prototype: Is this what you suggest?
```
<entry>
<info L="7668" page="5.223" gtypes="S,D,F"/>
<S n="7668">
<s>amitaguRo 'pi padArTo dozeREkena nindito Bavati .</s>
<s>niKilarasAyanamahito ganDenogreRa laSuna iva .. 7668 ..</s>
</S>
<D n="7668">
<b>7668.</b>
</D>
<F n="7668">
7668) SPHUṬAŚLOKA. ²c. <s>sakala</s> st. <s>niKila</s> v. l.
</F>
</entry>

<entry>
<info L="7668.1" page="5.223" gtypes="HS"/>
<HS>
<s>amuM kAlakzepaM</s> u. s. w. herausgegeben von
TH. AUFRECHT a. a. O. S. 4. 5.
In ²d. ist bei AUFRECHT zu lesen: <s>°jvAlAvalijawila°</s>.
</HS>
</entry>

<entry>
<info L="7668a" page="6.4" gtypes="S"/>
<S>
<s>amuM kAlakzepaM tyaja jalada gaMBIramaDurEH</s>
<s>kimeBirnirGozEH sfja rawiti rAMkAri salilaM .</s>
<s>aye paSyAvasTAmakaruRasamIravyatikara-</s>
<s>jvalahAvajvajvAlAjawilamUrterviwapinaH ..</s>
</S>
<D n="7668a">
"Was, Wolke ... wird." pa1n2au 133,21:
</D>
<F n="7668a"> 1) b. jha1tka1ri A. B. O. jha1tka1ra D. tatka1ri E.
</F>
</entry>

And then the next entry from 'volume 5'
<entry>
<info L="7669" page="5.223" gtypes="S,D,F"/>
<S n="7669">
<s>amuzminnudyAne vihagaKala eza pratikalaM</s>
<s>vilolaH kAkolaH kvaRati Kalu yAvatkawutaram .</s>
<s>saKe tAvatkIra draQaya hfdi vAcaM ca sakalAM</s>
<s>na mOnena nyUno Bavati guRaBAjAM guRagaRaH .. 7669 ..</s>
</S>
... ETCETERA
</entry>
```

**Comment by thomasincambodia** [comment]
@funderburkjim 
almost, but not quite.
I suggest we discuss this on skype.

**Comment by funderburkjim** [comment]
@thomasincambodia  Talk about h3 now?

**Comment by Andhrabharati** [comment]
@funderburkjim 

Though out-of-context, as you'd say, posting my next update on bosep.

This time I looked at the V1, V2, V3 entries mainly.
[2nd update on boesp.pdf](https://github.com/funderburkjim/boesp-prep/files/7851475/2nd.update.on.boesp.pdf)
[boesp_deva (AB)_1a.txt](https://github.com/funderburkjim/boesp-prep/files/7851478/boesp_deva.AB._1a.txt)

In p. 620 of Vol. 3, the footnote says

> Da hier auch die Nachträge und Verbesserungen, welche sich am Schlusse der beiden ersten Theile befinden, wieder aufgenommen worden sind, so können jene unberücksichtigt bleiben oder auch vernichtet worden.

And indeed seen that almost all the V1 & V2 entries are in V3 as well (either as is or slightly updated), except V1-1318 & V2-898.

So, renaming these two as V3 entries and deleting the whole blocks of V1 & V2 could be done as suggested by Vol. 3 Footnote above, in discussion with @thomasincambodia.

[I had just reached halfway in proofing the Vol. 2 verses and took up this piece of work as a mind-changer.]

**Comment by Andhrabharati** [comment]
And here are the missed or wrong entries of V3 in digitization-
[missed V3 entries in digitization.txt](https://github.com/funderburkjim/boesp-prep/files/7851542/missed.V3.entries.in.digitization.txt)

**Comment by Andhrabharati** [comment]
> whereas` <h4>` elements are cross references to other Spr. and therefore comparable to `<HS>` elements,
> `<h3>` elements are not.
> 
> They are Spr. taken from Aufrecht and alphabetically ordered in the numbered list of additional entries in the 2nd additions and corrections in boesp5. I think these truncated entries should be completed by copying them from the original article (no big deal as there are only 13 of them) and then given their positional numbering plus, say, 'a'.
> The first occurrence of an Aufrecht Spr. would then be numbered 7668a i.e. <info L="7668a" [etc.] />
> 

I guess the German translations by Aufrecht would also be "done" along with the verses.

**Comment by Andhrabharati** [comment]
> @Andhrabharati vol. 3 verses prepared for you. See #49.

@funderburkjim 

The file is not posted in the boesp-prep-ab folder. [only the empty file is seen here!]

However, I have taken it from the boesp-prep/step4a1 folder.

Just FYI.

**Comment by funderburkjim** [comment]
Re empty file for vol 3 verses.

@Andhrabharati  Have reposted boesp-3_deva.txt to boesp-prep-ab repository.  
Glad you were able to find the copy in step4a1 directory.

**Comment by funderburkjim** [comment]
> German translations by Aufrecht

Yes, the plan is to also include these.   In the prototype above, note
```
<D n="7668a">
"Was, Wolke ... wird." pa1n2au 133,21:
</D>
```
Here, an abbreviated form of the German text is shown.  The full
German text will be provided.

Also, after discussion with @thomasincambodia ,  we concluded that there is a better place to put the 
Aufrecht entry.  For instance, the L="7668a" entry will instead be put AT THE END ,
as entry L="7866" (since the last supplemental Boehtlingk entry is L="7865").

**Comment by funderburkjim** [comment]
The 13 Aufrecht entries have been typed, but not yet put into boesp.xml.

@Andhrabharati  would you proofread?  The file is [step4e/aufrecht_entries2_deva.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4e/aufrecht_entries2_deva.txt).

Notes:
1. The Footnote has been written to be conformant to the general boesp usage, namely it should contain the reference source, with an occasional additional comment.  Since Aufrecht's format is different,  the reference source was inferred, and so should be checked.
2. There was one case where Boesp page reference was in error  
    `7791.1 -> 7873 <s>kaTamiha manuzyajanmA</s> page 62`
   Note above should be page 29.  Print error in vol 5 at 7791.1
   This also noted at [step0/boesp_printchange.txt]().
3. I forgot to change the page at L=7873 to 29 in commit 17359b5.  The change is made at
    commit 59d1037.

Maybe @thomasincambodia should also check, especially the German text, and the footnote.

When proofread, the Aufrecht entries will be inserted at the end of boesp.xml.

**Comment by Andhrabharati** [comment]
Sure.

**Comment by Andhrabharati** [comment]
Finished reading the full text.
[aufrecht_entries2_deva.txt](https://github.com/funderburkjim/boesp-prep/files/7860617/aufrecht_entries2_deva.txt)

**Comment by Andhrabharati** [comment]
3 minor updates in FN markings-
[aufrecht_entries2_deva_updated.txt](https://github.com/funderburkjim/boesp-prep/files/7863456/aufrecht_entries2_deva_updated.txt)

**Comment by funderburkjim** [comment]
## Different kinds of double quotes
The text of the German translation of each of the Aufrecht verses is enclosed in opening/closing double quotes.
In my coding, I used the Unicode QUOTATION MARK " U0022 for both.
The updated version uses 
*  `„ DOUBLE LOW-9 QUOTATION MARK U201E` for opening quotation mark and 
*  `„ DOUBLE LOW-9 QUOTATION MARK U201E` for closing quotation mark.

Since this agrees visually with the pdf, the updated version is accepted.

Incidentally, in the body of boesp.xml, the unicode characters used for quotation mark are:
*  `«  (\u00ab)  LEFT-POINTING DOUBLE ANGLE QUOTATION MARK`
*  `»  (\u00bb)   RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK`

This choice agrees visually e.g. in the VN material from volume 1 (page 435)
![image](https://user-images.githubusercontent.com/6393033/149418669-4ce63cb9-2263-49dc-8619-bd0880dbd0f7.png)

@thomasincambodia  Is there a way to make sense of these variations in double quotes in German text?

**Comment by funderburkjim** [comment]
Aside from the double-quote differences, and after the adjustment with umlauts, there are 23 corrections made by the updated version. See [changes_entries2a.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4e/changes_entries2a.txt).  

One change perhaps should be reviewed.
![image](https://user-images.githubusercontent.com/6393033/149419710-5f7fda1a-8f39-4583-a3a9-e206a731287d.png)
```
<s>ज्वलद्दावज्वाला[वलि]जटिलमूर्तेर्विटपिनः ॥</s>
; filled up [वलि] to make the verse metrically correct. (Taken from another ed. of Sār.Pad.)
```
Should we keep this revision? If so, it should be mentioned, perhaps in step0/boesp_printchange.txt

Will wait another day or so for possible further comments/corrections.

**Comment by drdhaval2785** [comment]
We should make this print change. 

Is there an addenda corrigenda at the end? Usually such cases get enumerated there in the last volume of book in multi volume books. 

Even if it is not in corrigenda, we should rdctify metrical error based on another edition as suggested. Note the change in printchange.

Agree with the proposal.

**Comment by thomasincambodia** [comment]
> ## Different kinds of double quotes
> The text of the German translation of each of the Aufrecht verses is enclosed in opening/closing double quotes. In my coding, I used the Unicode QUOTATION MARK " U0022 for both. The updated version uses
> 
> * `„ DOUBLE LOW-9 QUOTATION MARK U201E` for opening quotation mark and
> * `„ DOUBLE LOW-9 QUOTATION MARK U201E` for closing quotation mark.
> 
> Since this agrees visually with the pdf, the updated version is accepted.
> 
> Incidentally, in the body of boesp.xml, the unicode characters used for quotation mark are:
> 
> * `«  (\u00ab)  LEFT-POINTING DOUBLE ANGLE QUOTATION MARK`
> * `»  (\u00bb)   RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK`
> 
> This choice agrees visually e.g. in the VN material from volume 1 (page 435) ![image](https://user-images.githubusercontent.com/6393033/149418669-4ce63cb9-2263-49dc-8619-bd0880dbd0f7.png)
> 
> @thomasincambodia Is there a way to make sense of these variations in double quotes in German text?

@funderburkjim 
These quotation marks are French printing conventions (also putting the table of contents at the end of a book).
They would have been taken over by  the printing press of the Russian Academy of Sciences in Petersburg.

In German printing the "English" system is predominant,
but  French quotation marks are sometimes also used in German publications. 
(Putting the table of contents at the end of a book was common in East German publications.)

**Comment by Andhrabharati** [comment]
> Aside from the double-quote differences, and after the adjustment with umlauts, there are 23 corrections made by the updated version. See [changes_entries2a.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4e/changes_entries2a.txt).
> 
> One change perhaps should be reviewed. ![image](https://user-images.githubusercontent.com/6393033/149419710-5f7fda1a-8f39-4583-a3a9-e206a731287d.png)
> 
> ```
> <s>ज्वलद्दावज्वाला[वलि]जटिलमूर्तेर्विटपिनः ॥</s>
> ; filled up [वलि] to make the verse metrically correct. (Taken from another ed. of Sār.Pad.)
> ```
> 
> Should we keep this revision? If so, it should be mentioned, perhaps in step0/boesp_printchange.txt
> 
> Will wait another day or so for possible further comments/corrections.

jvAlA is singular and jvAlAvali is plural, and we can see the plural form clearly in the German translation, though missed in the print verse, as "Flammenmeer" (Sea of Flames).

This indicates that this is a print error to be corrected.
[**I had come across the first one in Aufrecht's work now!**]

**Comment by Andhrabharati** [comment]
> * `„ DOUBLE LOW-9 QUOTATION MARK U201E` for closing quotation mark.

This should've been

„ DOUBLE HIGH-9 QUOTATION MARK U201F for closing quotation mark.

**Comment by funderburkjim** [comment]
## 17 syllables
The verse in question (L=7866)
```
<s>amuM kAlakzepaM tyaja jalada gaMBIramaDurEH</s>
<s>kimeBirnirGozEH sfja Jawiti JAMkAri salilam .</s>
<s>aye paSyAvasTAmakaruRasamIravyatikara-</s>
<s>jvaladdAvajvAlA[vali]jawilamUrterviwapinaH ..</s>
```
Here is breakup into syllables, of which there are 17 in each 'pada'
```
<s>a muM kA la kze paM tya ja ja la da gaM BI ra ma Du rEH</s>  17
<s>ki me Bi rni rGo zEH sf ja Ja wi ti JAM kA ri sa li lam .</s>  17
<s>a ye pa SyA va sTA ma ka ru Ra sa mI ra vya ti ka ra-</s>  17
<s>jva la ddA va jvA lA va li ja wi la mU rte rvi wa pi naH ..</s> 17  
```
Are there errors in my identification of syllables?

**Comment by funderburkjim** [comment]
## sea of flames?

jvalAvali = jvalA-Avali = flames-row

How do we get flames-*sea* ?

**Comment by funderburkjim** [comment]
## keep the square brackets?

Should we keep the square brackets around the added part `[vali]` ?

**Comment by funderburkjim** [comment]
## quotation marks
This table summarizes ([Reference](https://www.thoughtco.com/german-zeichensetzung-punctuation-marks-4082218)):
![image](https://user-images.githubusercontent.com/6393033/149566132-d0532611-2171-4216-be01-6d18bd957070.png)

**Comment by Andhrabharati** [comment]
> ## sea of flames?
> 
> jvalAvali = jvalA-Avali = flames-row
> 
> How do we get flames-_sea_ ?

Guess, you might've noticed the lit. & fig. abbr.s in various dictionaries.

This particular one comes under figurative translation [The range of flames "as wide and spread as" a Sea], not a literal traslation.

**Comment by Andhrabharati** [comment]
> ## keep the square brackets?
> 
> Should we keep the square brackets around the added part `[vali]` ?

The standard practice in filling up the missed text in the work under consideration is to enclose in [...].
As such I had put the two letters thus.

If there is no need for 'strict' adherence to the printed text here, these can be removed without any impact. [Probably just marking it as a print-change somewhere.]

**Comment by Andhrabharati** [comment]
@funderburkjim 

Finished "reading" the full V1-V5 data, and found that the h3 entries are actually variants for the Aufrecht's 13 verses.

Also one V5 entry 5299 is missed in the digitization.

And this jvalAvali as a print change is mentioned in the V5, putting a stop to all further discussions on the point!

Here are the updated files-
[V1 to V5 updates on boesp.pdf](https://github.com/funderburkjim/boesp-prep/files/7877230/V1.to.V5.updates.on.boesp.pdf)
[aufrecht_entries2_deva_updated.txt](https://github.com/funderburkjim/boesp-prep/files/7877231/aufrecht_entries2_deva_updated.txt)
[last V4 entries & missed V5 entry.txt](https://github.com/funderburkjim/boesp-prep/files/7877238/last.V4.entries.missed.V5.entry.txt)
[boesp_deva (AB)_1b.txt](https://github.com/funderburkjim/boesp-prep/files/7877239/boesp_deva.AB._1b.txt)

**Comment by Andhrabharati** [comment]
Now, only the Footnotes portion remains to be "read" once.
[I have already finished proofing the Vol. 2 verses and would be posting the file, when Sampada does her portion!]

**Comment by Andhrabharati** [comment]
And what does @thomasincambodia say, about using the V1-V5 data as corrigenda to be "integrated" into the main text as appripriate?

**Comment by funderburkjim** [comment]
The latest commit 878cdb9 adds the aufrecht entries, and the missing v3,v4,v5.

It also includes the corrections present in boesp_deva(AB)_1b.txt.

Directory [step4f](https://github.com/funderburkjim/boesp-prep/tree/main/step4f) describes the analysis.

@Andhrabharati   It took quite a bit of time to discover what you had done and to
integrate your changes in a safe way.

Before you begin to do further edits, please let's discuss (in another issue).

And, thanks for the improvements to boesp.

I think this issue can now be closed. Agree?

**Comment by funderburkjim** [comment]
> The range of flames "as wide and spread as" a Sea

Thanks for the explanation.  Probably this kind of figurative usage is frequent, and must be learned by experience.
