### ISSUE TITLE
transcoding boesp.xml

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#43]
This relates to work in step3e directory.

In step0/boesp_utf8.xml at commit ef22c7e9e , the Sanskrit text (within `<s>` elements) is represented in the HK transliteration.

The aim of step3e is to first convert to the SLP1 transcoding, for consistency with the rest of 
sanskrit-lexicon (such as the dictionary digitizations at [csl-orig](https://github.com/sanskrit-lexicon/csl-orig).
This version will be named step0/boesp.xml, and this form will be the base for further revisions.

Other encodings will be derived from boesp.xml by transcoding, and will be named
* boesp_hk.xml (this will initially be the same as step0/boesp_utf8.xml at commit ef22c7e9e)
* boesp_deva.xml Devanagari unicode
* boesp_iast.xml   (Latin alphabet with diacritics).

**Comment by funderburkjim** [comment]
The transcoded versions are now available in step0 directory.

Note: boesp_utf8.xml will no longer be modified.  The 'hk' version (step0/boesp_hk.xml)
will be maintained, as well as the deva and iast versions.

**Comment by Andhrabharati** [comment]
@funderburkjim 

One last step of (minor) corrections done at my end, in the boesp_deva file.
1. Majority of them are 'extra' spaces at the beginning or ending inside the `<s>...</s>` or `<g>...</g>` tags.
2. When a verse is split at a composite sandhi (or samAsa) word into a sep. line, it is commonly marked with a hyphen.
3. ... ... ... 
[other corrections are self-explanatory.]

Posting the diff file as pdf, and the xml file as txt file, for easy tracking.
[some minor corrections in boesp.pdf](https://github.com/funderburkjim/boesp-prep/files/7835061/some.minor.corrections.in.boesp.pdf)
[boesp_deva (AB)_1.txt](https://github.com/funderburkjim/boesp-prep/files/7835065/boesp_deva.AB._1.txt)

[I had removed the ls tagging, that was just initiated with plain 'R.' without edition references.]

**Comment by Andhrabharati** [comment]
(95240) may be corrected as **Fuss ᴗᴗᴗ–!** from **Fuss {?!}**.

**Comment by funderburkjim** [comment]
AB Corrections of previous two comments now analyzed and installed as commit fa76ceb.

Another view of details:
* See [step4d/readme.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4d/readme.txt) from *temp_boesp_deva.AB._1.txt* through *temp_boesp_10.xml*.
* For the 'nec' (not-elsewhere-classified) changes, see also [step4d/change_09.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4d/change_09.txt)


One wrinkle: There was a duplicate line (line 158357 ) that needed to be deleted.
Such line deletions require special handling, since a deletion changes the number of lines.
In this case, I handled it manually after all the other changes.
