### ISSUE TITLE
Sanskrit text vol. 1, 2nd revision

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#44]
In [sanproof_1_01
](https://github.com/funderburkjim/boesp-prep/tree/main/step1a/sanproof_1_01)
@Andhrabharati  and @sanskritisampada  provided proofreading of Sanskrit verses from Volume 1.
This resulted in differences in 320 lines (https://github.com/funderburkjim/boesp-prep/blob/main/step1a/sanproof_1_01/diff_verses.txt).

They have provided additional revisions for these 320, and this issue notes the analysis of the revision.

**Comment by funderburkjim** [comment]
See [sanproof_1_02](https://github.com/funderburkjim/boesp-prep/tree/main/step1a/sanproof_1_02).
There are now differences in 76 lines.
See [diff_verses1.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step1a/sanproof_1_02/diff_verses1.txt).  In these, each line of the 76 differences is shown in two forms, the first according to @sanskritisampada  and the second according to @Andhrabharati.

Each pair is further annotated by me, in consultation with the boesp-1 pdf.
The line which I thought was correct has a '+'.

[diff_verses1_abreview_deva.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step1a/sanproof_1_02/diff_verses1_abreview_deva.txt) has just the verses which should be reviewed by @Andhrabharati.

Similarly, [diff_verses1_samreview.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step1a/sanproof_1_02/diff_verses1_samreview.txt) has just the verses which should be reviewed by @sanskritisampada.

**Comment by funderburkjim** [comment]
The corrections to Sanskrit for volume 1 now installed in step0/boesp.xml,
and in the other transcodings (step0/boesp_hk.xml, etc.)

**Comment by Andhrabharati** [comment]
Checked my file and the remarks marked in here-

[diff_verses1_abreview_deva (AB remarks).txt](https://github.com/funderburkjim/boesp-prep/files/7798478/diff_verses1_abreview_deva.AB.remarks.txt)

**16 proof errors!! I need to improve my reading still.**

**Comment by funderburkjim** [comment]
[Commit  3e2c8a990](https://github.com/funderburkjim/boesp-prep/commit/3e2c8a990c234cbb5e50e4a3b6f098c6e2954219)  makes corrections to the *page* parameter of the info element of the entries.  This problem was mentioned when HS elements were separated out (see [this comment](https://github.com/funderburkjim/boesp-prep/issues/39#issuecomment-1000615022)).

Also, two missing HS elements were inserted.

The changes can also be reviewed in this diff file: [step4a/diff_pagechanges.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4a/diff_pagechanges.txt).

**Comment by funderburkjim** [comment]
@Andhrabharati  Your diff file should be fine. Plan to make use of it tomorrow. Thanks!

**Comment by funderburkjim** [comment]
## print changes
Above commit c774b7c installs several print changes based on AB's diff remarks.

A file [boesp_printchange.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step0/boesp_printchange.txt) documents these changes.

And the intention is to use the boesp_printchange.txt file to similarly document other print changes that may arise.

**Comment by Andhrabharati** [comment]
https://github.com/funderburkjim/boesp-prep/issues/48#issue-1097410059

Thus, guess this issue can be closed now.
