### ISSUE TITLE
AS convert to IAST

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#45]
Now ready to convert the AS (letter-number) coding of boesp.xml to standard IAST (letters with diacritics).

**Comment by funderburkjim** [comment]
Several changes (about 100) were made in word-spelling before changing from letter-number to letter-diacritic.
These can be seen in the commit 879ed2e  And also in [step4b/change_01.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4b/change_01.txt).

**Comment by funderburkjim** [comment]
The version of boesp.xml with IAST coding is computed. 
See files in commit c594eb3.

* [words_letternums_iast.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4b/words_letternum_iast.txt) shows a frequency count of the words changed, along with the new iast spelling
* [letternums_iast.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4b/letternums_iast.txt) contains the letter-number sequences that are to be converted, and the diacritic to which each is converted.
  * noticed that M3, m3 were used in the coding for anusvara.  Normally, m3 would be changed to m-dot-above.  But since the standard iast for anusvara is m-dot-below,  our converse will change m3 to m-dot-below, and similarly for M3.
* [change_02.xml](https://github.com/funderburkjim/boesp-prep/blob/main/step4b/letternums_iast.txt) shows the changes to each of the 10102 lines changed.
   * This is accidentally named '.xml', but it is just a text file.

**Comment by Andhrabharati** [comment]
Sorry for posting on a closed issue @funderburkjim; but I was waiting for this LN style conversion to happen, to check the text once.

Just looked for the small letter followed by a CAP letter, and found some occurrences, wherein all but one needed correction.
[Some are of Sanskrit text, some for names (authors or works), ...]

These are due to missing parenthesis, missing/wrong tagging or a typo etc.
[small letter followed by CAP letter.txt](https://github.com/funderburkjim/boesp-prep/files/7820387/small.letter.followed.by.CAP.letter.txt)

1. Proofing for Sanskrit throughout would take care of the wrong/missing tags (remaining, if any).
2. Other typos etc. would come out while working on ls tagging.
3. ... ...

**Comment by Andhrabharati** [comment]
Seen 31 places where having a space would be better (or required) in between `><`, as `> <`.

**Comment by Andhrabharati** [comment]
There are two places still having a letter followed by number.

(50226): 2102. (830.)  Ὑπὸ τῆς σφοδρᾶς περιβολῆς οἱ μαστοὶ αὐτῆς ϰαταπε-[Seite1.412]πιεσμένοι εἰσίν, τὰ δὲ τρίχια ὀρϑὰ ἕστηϰε, τῇ δ’ ὑπερβολῇ τῆς ἐτιϑυμίας τὸ ϰαλὸν παραμηρίδιον ϰαταρρεῖ· “μὴ μή, ὦ ἐμὸν ἀγλάισμα, μὴ ἄγαν ἐμέ — ἃλις“ οὕτω ϰεϰλασμένῃ τῇ φωνῇ φϑεγγομέη πότερον ϰαταδεδάρϑηϰεν ἢ τέϑνηϰεν ἢ εἰς τὴν έμὴν ϰαρδίαν εἰσδέδυϰεν ἢ τέτηϰεν;
**Here the regular <pb marking could be used.**

(80389): 3358) MBH. ä3, 1829.
**Here it is- MBH. 13, 1829.**
And this reminds me the necessary correction in the citation references as done in pwk recently (as per the print)- to remove the space after a comma between `[0-9], [0-9]`.

`-----------`
And then, there are some places where the number followed by letter need a correction.

(32511): 198ed. JOHNS. 218. ²a. कष्टस्य st.
**This should be- 198. ed. JOHNS. 218. ²a. कष्टस्य st.**

(32993): Hindoos I, 13 (3ed. London 1817).
**This should be- Hindoos I, 13 (3 ed. London 1817).**

(54699): 2290) CĀṆ. 41bei HAEB. 315.
**This should be- 2290) CĀṆ. 41 bei HAEB. 315.**

(103867): 4340) MBH. 5, 1145. 12m 861, ²b. 862,
**This should be- 4340) MBH. 5, 1145. 12, 861, ²b. 862,**

(152584): 1151fg. 6415, ²d. सर्वदा die neuere
**This should be- 1151 fg. 6415, ²d. सर्वदा die neuere**

**Comment by Andhrabharati** [comment]
There are 269 lines having a space at the line-ending.

**Comment by Andhrabharati** [comment]
There are over 2000 double spaces.

**Comment by Andhrabharati** [comment]
Few quick corrections-
```
<s>ंअट</s>	<s>माता</s>
<s>ंउर्खत्वं	<s>मूर्खत्वं
<s>बृ{?} ंटिं</s>	<s>बृंटिं</s>
<s>बृ{?} ंटीनामाचा	<s>बृंटीनामाचा
वातावधू{?} ं	वातावधूतं
(-Azrayam)	(= <s>आश्रयम्</s>)
(Agastja)	(Agastya)
<wide>arjuna	<wide>Arjuna
galan.	GALAN.
kull.	KULL.
s'l.	śl.
varr.	Varr.
vatt.	Varr.
varna	varṇa
```

**Comment by Andhrabharati** [comment]
Here are the 51 {?}places marked correctly-

```
<s>अहो{?} पिशुनसर्पस्य	<s>अहो पिशुनसर्पस्य
ऽ४{?} क्षयं	ऽक्षयं
मानव्{?} म्	मानवम्
कि{?} मिति	किमिति
ततो ऽपि गलितो{?}	ततो ऽपि गलितो २
क्लान्तेव{?} कान्ताजनैः	क्लान्तेव कान्ताजनैः
<s>मक्षिका</s> {?}	<s>मक्षिका</s> ᴗᴗ–
चत्वारस्तूपचीयन्त{?}	चत्वारस्तूपचीयन्ते
ह{?} ठात्	हठात्
स्वरो{?} गतेर्भङ्गो	स्वरो गतेर्भङ्गो
चेद्गेहि{?} निम्,	चेद्गेहिनीम्,
सक{?} लं	सकलं
काले{?} न	कालेन
मानभ्रंशकरः {?} स्मरेण	मानभ्रंशकरः स्मरेण
प्रशान्त्{?} त्मा	प्रशान्तात्मा
त्वमलमाशङ्क{?} त्र	त्वमलमाशङ्कयात्र
पश्य्{?} दुपक्रमम्	पश्येदुपक्रमम्
क्वचित्किं{?} त्कदाचन	क्वचित्किंचित्कदाचन
HIT. {?}	HIT. ²c.
{?} र्यनुयोगः	पर्यनुयोगः
दधातु{?}	दधाति
पिक{?} पक्षिणाम्	पिकपक्षिणाम्
सैक्ष्यम्; अख{?} य्यं	भैक्ष्यम्; अखय्यं
GALALANOS	GALANOS
<s>अक्ष{?} \nय्यं</s>.	<s>अक्षय्यं</s>.
शीलाड्यं{?}	शीलाढ्यं
चित्तध्यानविवेकवि{?} हलधियां,	चित्तध्यानविवेकविव्हलधियां,
<s>कुलीना</s> im \nfolgenden <wide>Śloka</wide> {?} \ngegenuberstehen.	<s>कुलीना</s> \nimfolgenden Śloka gegenuberstehen.
सुओतः{?}	सुप्तः
तद्दू{?} भ्यां	तद्द्वाभ्यां
4383. = {?} AITRYUP.	4383. = MAITRYUP.
मा {?} दुर्बलचक्षूंषि	मा त्वां दुर्बलचक्षूंषि
CĀṆ. {?} bei	CĀṆ. 51 bei
तत्{?} क्षणान्मेरुः	तत्क्षणान्मेरुः [are the 4-liner verses not marked thus in Vol.3 text?]
तथापि कृ{?}णा	तथापि कृपणा
कर्मदिषांश्च	कर्मदोषांश्च
क्{?} र्मदोषांस्तु	कर्मदोषांस्तु
धनाद्ये{?} षु	धनाढ्येषु
सदैवापद्गतो{?} राजा	सदैवापद्गतो राजा
BHĀMINIVILA{?}	BHĀMINĪVILASA
युवतौ {?}	युवतौ च
शुचि{?} भमिगतं	शुचिर्भूमिगतं [print error; cf. with the d. i. given next - शुचि भूमि॰]
पलप्र{?} णं	पलप्रमाणं
<s>{?} तन्मयं</s>	<s>तं<</s> st. <s>तन्मयं</s>
ऽप्यहो {?} रपतिं	ऽप्यहो नरपतिं
{?} edition	l'édition
44, {?} ²a.	44, 9. ²a.
बधाय{?}	बधायः
अर्थितो बुआध्{?} मूर्खः	अर्थितो व्याधितो मूर्खः
न{?} गृहं	न गृहं
वदा{?}	वदामि
```

**Comment by funderburkjim** [comment]
Glad to receive the corrections posted.  Beginning to work on incorporating them into boesp.xml.

**Comment by Andhrabharati** [comment]
Finally, this is the updated file at my end as of now-
[boesp_deva (AB).txt](https://github.com/funderburkjim/boesp-prep/files/7823646/boesp_deva.AB.txt)
[changed the extension to .txt from .xml]

**Comment by funderburkjim** [comment]
Commit a189843 contains corrections from boesp_deva (AB).txt from 2 lines up.
Over 2800 lines changed.
See [step4d readme](https://github.com/funderburkjim/boesp-prep/tree/main/step4d) for details.

The approach taken was to compare the AB file just mentioned with the latest prior boesp.xml.

> NOTE:  This updated file was very useful.  Only minor quibble.  It had 1 fewer lines than the
prior boesp.xml,  This was because lines 98824-5 were merged as part of a correction in the AB file.
It was a bit tedious to discover this detail, and adjust for it so further analytical tools were available.
In future, better to either keep the number of lines in a revised file unchanged, or communicate to me intentional lines deleted (or added).

There were numerous small 'punctuation'-type changes made. These are mentioned in the discussion of temp_boesp_01.xml through temp_boesp_04.xml in the step4d readme file.

Aside from these, there were about 270 changes, which are listed in [change_05.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4d/change_05.txt).
Many (perhaps all) of these are discussed in AB's comments above.

There were a small number of changes NOT made, or made in a slightly different way.
These are in [change_not_made.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4d/change_not_made.txt).
1. DIfference in value of 'version' parameter.
2.  omission of `<ls>` tagging:  The AB file did these only in a few cases.  We may at some future
    revision want to add such tagging comprehensively.
3. In one Greek text, there was an 'embedded' [Seitexxx] which AB file changed to `<pb.../>`.  I moved this out of the `<g>Y</g>`.  While the resulting location if the pb is slightly inaccurate, the relocation will make for easier further processing.

**Comment by funderburkjim** [comment]
@Andhrabharati  I think it is ok to close this now.  If you agree, go head and close the issue.

**Comment by Andhrabharati** [comment]
I had indicated the merger thus
> <s>कुलीना</s> im \nfolgenden <wide>Śloka</wide> {?} \ngegenuberstehen.	<s>कुलीना</s> \nimfolgenden Śloka gegenuberstehen.

though not explicitly worded.

 Sorry for the trouble given.

I would remember to keep a blank line if such mergers are done by me in future, which could be removed later.

**Comment by Andhrabharati** [comment]
> In future, better to either keep the number of lines in a revised file unchanged, or communicate to me intentional lines deleted (or added).

Two pending works that would "add" lines in the files-

1. Unlike the German translation paragraphs that are broken into smaller lines, the Greek translations are retained as a single L O N G line. Probably these could also be split into smaller lines.
2. The 4-liner verses in the volume-3 seem not to have been put thus (as has been done in Volumes 1 & 2), but kept as 2-liners. These should also be split to make the text uniform throughout.

I request @funderburkjim to look into these two points also and then close the issue.

**Comment by funderburkjim** [comment]
The long verses in volume 3 now reformatted with 4 lines.
415+ such verses found.  A list is in the 'temp_boesp_06' section of [step4d/readme.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4d/readme.txt)

Also checked that the long verses in volume 5 (melanges asiatiques, tome viii, 1877), have been
similarly formatted.

Also, the vol1/2 long verses have been previously reformatted, though no further review of these was done at this time.  

It is believed that all long verses, in whatever volume, have been reformatted.



Will next take a look at reformatting the long greek texts.

**Comment by funderburkjim** [comment]
Reformatted long Greek text lines into several shorter lines.
The breaks arbitrary; often introduced line breaks after comma within greek text.

Closing issue.
