### ISSUE TITLE
Proof-reading sanskrit verses, vol 2.

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#48]
We have dealt with proof-reading of Sanskrit verses from Volume 1.
Now let's do proof-reading of Sanskrit verses from Volume 2.

**Comment by funderburkjim** [comment]
[step4a1/verses_02.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4a1/verses_02.txt) copied to boesp-prep-sam repository as file
sanproof/boesp-2_slp1.txt.   This is for proofreading by @sanskritisampada.


[step4a1/verses_02_deva.txt](https://raw.githubusercontent.com/funderburkjim/boesp-prep/main/step4a1/verses_02_deva.txt) copied to boesp-prep-ab repository as file
sanproof/boesp-2_deva.txt.  This is for proofreading by @Andhrabharati.

**Comment by funderburkjim** [comment]
Note on new format:  You'll notice the change in format.  This was done to make it easier for me to
move the changes back into the full boesp file.  
Hope this is easy for the proofreaders to adapt to.

**Comment by funderburkjim** [comment]
Comparison of revisions by @Andhrabharati and @sanskritisampada now done.
There were 25 differences.

Candidate for final revision prepared: step4a2/boesp-2_slp1_final.txt

13 differences between @Andhrabharati revision and  'final' version:
  step4a2/boesp-2_slp1_diff_ab2a_final.txt  (slp1 version)
  [boesp-2_deva_diff_ab2a_final.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4a2/boesp-2_deva_diff_ab2a_final.txt)  (devanagari version)
 
15 differences between @sanskritisampada revision and 'final' version:
  [step4a2/boesp-2_slp1_diff_sam1b_final.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4a2/boesp-2_slp1_diff_sam1b_final.txt)

Two intentional print changes included:
```
 3198 old <s>na kiMtkvicidastIha vastvasADyaM vipaScitAm .</s>
 3198 new <s>na kiMcitkvacidastIha vastvasADyaM vipaScitAm .</s>
 2646 old <s>triviDAH puruzA rAjannutamADamamaDyamAH .</s>
 2646 new <s>triviDAH puruzA rAjannuttamADamamaDyamAH .</s>
```

Also noted comment `; this line not needed here. <pb n="2.106"/>` re L=2731,2732.

Request @Andhrabharati and @sanskritisampada to review the remaining diffs between their latest version
and the 'final' candidate,  and to mention any changes required in 'final'.

**Comment by Andhrabharati** [comment]
Gone through the data again, and submit that

- My file needs correction at v.2342, v.2918, v.3358, v.3459, v.3562, v.4086 and v.4487.
[It may be noted that v.4086 is not in the diff file by Jim.]

- In three cases, v.2495, v.2642, v.2743, the spacing may be retained or removed in my file (changed for better clarity), as per the print.

And here is the diff file with my comments--
[boesp-2_deva_diff_ab2a_final (AB comments).txt](https://github.com/funderburkjim/boesp-prep/files/8440494/boesp-2_deva_diff_ab2a_final.AB.comments.txt)


`--------------------`
**Some doubts:**

1.  The correction in v.3198 is mentioned in V5, so would it go as a **print correction** or go with the (**un-integrated**) V5 data?

2. > Also noted comment ; this line not needed here. <pb n="2.106"/> re L=2731,2732.

      does this mean the line (`<pb n="2.106"/>` after v.2731) would be present or removed?

**Comment by funderburkjim** [comment]
## final1 
Received comments from above diffs in files:
 from Sampada:       [boesp-2_slp1_diff_sam1b_final.comments.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4a2/boesp-2_slp1_diff_sam1b_final.comments.txt)
 from Andhrabharati: [boesp-2_deva_diff_ab2a_final.AB.comments.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4a2/boesp-2_deva_diff_ab2a_final.AB.comments.txt)
My discussion in file:
 [boesp-2_final1_comment.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4a2/boesp-2_final1_comment.txt)

I made changes to boesp-2_slp1_final.txt, the results are in
  [boesp-2_slp1_final1.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step4a2/boesp-2_slp1_final1.txt).

These changes have been installed into [boesp.xml](https://github.com/funderburkjim/boesp-prep/blob/main/step0/boesp.xml).

print changes have been documented for 6 verses (see final1_comment file above, or [print_changes.txt](https://github.com/funderburkjim/boesp-prep/blob/main/step0/print_changes.txt).

>  3198 correction is one of the print changes  (per AB inquiry above)
    the `<pb n="2.106"/>` line after v.2731 is removed

The suggested print changes at v.2642 and v.2743 have not been made.  Not sure if further discussion needed.

Believe we can consider this 'Proof-reading sanskrit verses, vol 2.' as completed.

**Comment by Andhrabharati** [comment]
@funderburkjim 

https://github.com/funderburkjim/boesp-prep/issues/48#issuecomment-1091187102
As per my above post reg. the spacing after 'A', like to suggest that two vol.1 verses (v.1053, v.1779) also be 'modified' for the same.

**Comment by Andhrabharati** [comment]
Just found some overlooks in vol.1 and vol.2, that need correction--
L="1154:	उगम् तपः > उग्रं तपः
L="4023.1:	सदोषम् वा > सदोषं वा
L="4199:	छेदनम् स्मृतम् > छेदनं स्मृतम्

**Comment by drdhaval2785** [comment]
@funderburkjim Are the above 3 items still pending to be corrected or corrected already?
