### ISSUE TITLE
Sample form for sanskrit proofreading

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep#8]
@Andhrabharati   @sanskritisampada 

Take a look at the sample documents below.  Is the format adequate for your upcoming proofreading of
the Sanskrit verses in Indische Sprüche ?

When the format is agreeable, one or more documents will be generated containing all the 2000+ verses
in volume 1 of the book.

**Comment by funderburkjim** [comment]
## slp1 form
@sanskritisampada   I presumed you would want to proofread using slp1 spellings, so that's what is in this sample
```
; ---------------------------------------------
; 1 : page 1.1
    aMSo 'pi duzwadizwAnAM parezAM syAdvinASakft .
    vAlaleSo 'pi vyAGrARAM patsyAjjIvitahAnaye ..
; ---------------------------------------------
; 2 : page 1.1
    akaRWasya kaRWe kaTaM puzpamAlA vinA nAsikAyAH kaTaM DUpaganDaH .
    akarRasya karRe kaTaM gItanftyamapAdasya pAde kaTaM me praRAmaH ..
; ---------------------------------------------
; 3 : page 1.1
    akaruRatvamakAraRavigrahaH paraDane parayoziti ca spfhA .
    svajanabanDujanezvasahizRutA prakftisidDamidaM hi durAtmanAm ..
; ---------------------------------------------
; 4 : page 1.1
    akarmaRAM vE BUtAnAM vfttiH syAnnahi kA ca na .
    tadevABiprapadyeta na vihanyAtkadA ca na ..
; ---------------------------------------------
; 5 : page 1.2
    akarmaSIlaM ca mahASanaM ca lokadvizwaM bahumAyaM nfSaMsam .
    adeSakAlajYamanizwavezametAngfhe na prativAsayeta ..
; ---------------------------------------------
; 6 : page 1.2
    akasmAtprakriyA nf2RAmakasmAccApakarzaRam .
    SuBASuBe mahattvaM ca prakartuM budDilAGavam ..
; ---------------------------------------------
; 7 : page 1.2
    akasmAdiha yaH kaScidarTaM prApnoti pUruzaH .
    taM haWeneti manyante sa hi yatno na kasyacit ..
; ---------------------------------------------
; 8 : page 1.2
    akasmAdeva kupyanti prasIdantyanimittataH .
    SIlametadasADUnAmaBraM pAriplavaM yaTA ..
; ---------------------------------------------
; 9 : page 1.2
    akasmAdeva tanvaNgI jahAsa yadiyaM punaH .
    nUnaM prasUnabARo 'syAM svArAjyamaDitizWati ..
; ---------------------------------------------
; 10 : page 1.2
    akasmAdeva yaH kopAdaBIkzRaM bahu BAzate .
    tasmAdudvijate lokaH sasPuliNgAdivAnalAt ..
; ---------------------------------------------
; 11 : page 1.2
    akasmAddvezwi yo BaktamAjanmaparisevitam .
    na vyaYjane ruciryasya tyAjyo nfpa ivAturaH ..
; ---------------------------------------------
; 12 : page 1.3
+   <s>akasmAdyuvatI vfdDaM</s> s. Spr. <s>nAkasmAdyuvatI vfdDaM</s>.
    akARqakopino BarturanyAsaktoSca yozitaH .
    praSAntiScetasaH kartuM brahmaRApi na Sakyate ..
; ---------------------------------------------
; 13 : page 1.3
    akARqapAtajAtAnAmArdrARAM marmaBedinAm .
    gAQaSokaprahAraRAmacintOva mahOzaDam ..
; ---------------------------------------------
; 14 : page 1.3
    akAmasya kriyA kAciddfSyate neha karhicit .
    yadyadDi kurute kiMcittattatkAmasya cezwitam ..
; ---------------------------------------------
; 15 : page 1.3
    akAmAM kAmayAnasya SarIramupatapyate .
    icCatIM kAmayAnasya prItirBavati SoBanA ..
```

**Comment by funderburkjim** [comment]
## Devanagari form
@Andhrabharati ,  no doubt you want to proofread Devanagari .
```
; ---------------------------------------------
; 1 : page 1.1
    अंशो ऽपि दुष्टदिष्टानां परेषां स्याद्विनाशकृत् ।
    वाललेशो ऽपि व्याघ्राणां पत्स्याज्जीवितहानये ॥
; ---------------------------------------------
; 2 : page 1.1
    अकण्ठस्य कण्ठे कथं पुष्पमाला विना नासिकायाः कथं धूपगन्धः ।
    अकर्णस्य कर्णे कथं गीतनृत्यमपादस्य पादे कथं मे प्रणामः ॥
; ---------------------------------------------
; 3 : page 1.1
    अकरुणत्वमकारणविग्रहः परधने परयोषिति च स्पृहा ।
    स्वजनबन्धुजनेष्वसहिष्णुता प्रकृतिसिद्धमिदं हि दुरात्मनाम् ॥
; ---------------------------------------------
; 4 : page 1.1
    अकर्मणां वै भूतानां वृत्तिः स्यान्नहि का च न ।
    तदेवाभिप्रपद्येत न विहन्यात्कदा च न ॥
; ---------------------------------------------
; 5 : page 1.2
    अकर्मशीलं च महाशनं च लोकद्विष्टं बहुमायं नृशंसम् ।
    अदेशकालज्ञमनिष्टवेषमेतान्गृहे न प्रतिवासयेत ॥
; ---------------------------------------------
; 6 : page 1.2
    अकस्मात्प्रक्रिया नृ२णामकस्माच्चापकर्षणम् ।
    शुभाशुभे महत्त्वं च प्रकर्तुं बुद्धिलाघवम् ॥
; ---------------------------------------------
; 7 : page 1.2
    अकस्मादिह यः कश्चिदर्थं प्राप्नोति पूरुषः ।
    तं हठेनेति मन्यन्ते स हि यत्नो न कस्यचित् ॥
; ---------------------------------------------
; 8 : page 1.2
    अकस्मादेव कुप्यन्ति प्रसीदन्त्यनिमित्ततः ।
    शीलमेतदसाधूनामभ्रं पारिप्लवं यथा ॥
; ---------------------------------------------
; 9 : page 1.2
    अकस्मादेव तन्वङ्गी जहास यदियं पुनः ।
    नूनं प्रसूनबाणो ऽस्यां स्वाराज्यमधितिष्ठति ॥
; ---------------------------------------------
; 10 : page 1.2
    अकस्मादेव यः कोपादभीक्ष्णं बहु भाषते ।
    तस्मादुद्विजते लोकः सस्फुलिङ्गादिवानलात् ॥
; ---------------------------------------------
; 11 : page 1.2
    अकस्माद्द्वेष्टि यो भक्तमाजन्मपरिसेवितम् ।
    न व्यञ्जने रुचिर्यस्य त्याज्यो नृप इवातुरः ॥
; ---------------------------------------------
; 12 : page 1.3
+   <s>अकस्माद्युवती वृद्धं</s> s. Spr. <s>नाकस्माद्युवती वृद्धं</s>.
    अकाण्डकोपिनो भर्तुरन्यासक्तोश्च योषितः ।
    प्रशान्तिश्चेतसः कर्तुं ब्रह्मणापि न शक्यते ॥
; ---------------------------------------------
; 13 : page 1.3
    अकाण्डपातजातानामार्द्राणां मर्मभेदिनाम् ।
    गाढशोकप्रहारणामचिन्तौव महौषधम् ॥
; ---------------------------------------------
; 14 : page 1.3
    अकामस्य क्रिया काचिद्दृश्यते नेह कर्हिचित् ।
    यद्यद्धि कुरुते किंचित्तत्तत्कामस्य चेष्टितम् ॥
; ---------------------------------------------
; 15 : page 1.3
    अकामां कामयानस्य शरीरमुपतप्यते ।
    इच्छतीं कामयानस्य प्रीतिर्भवति शोभना ॥
```

**Comment by funderburkjim** [comment]
## PDF 
Just as a reminder,  A pdf of volume 1 (2nd edition) was provided by @gasyoun at https://github.com/sanskrit-lexicon/PWG/issues/37#issuecomment-898956536.   ([ref](https://github.com/sanskrit-lexicon/COLOGNE/issues/360)).

I think all you will need is the text file of verse (as in the sample) and the pdf.

**Comment by Andhrabharati** [comment]
go ahead to make the full text.

**Comment by Andhrabharati** [comment]
I would like to propose that @sanskritisampada can start off with her proofing as a 1st phase.
(Meanwhile, I will be on my AE proofing.)

I am presuming a week to 10 days time is needed at the max. to "read" all these verses.


Then I can do a 2nd round proofing on her work.

And finally @funderburkjim can have a glance into it, for integration with other portions of the text.

how does this proposal sound?

**Comment by Andhrabharati** [comment]
two other possibilities are 

1. doing full text parallelly, and compare both versions to get a final text
2. splitiing portions for individual working and joing the portions at the end

the parallel working and comparision is the better option out of these two, but I am presently engaged with AE (of course, a small break can be given to it).

splitting the portions and joing  the pieces makes it quicker, but has a minus point that only one proofing round took place on the whole.

**Comment by Andhrabharati** [comment]
which plan out of the three variants would get majority votes?

**Comment by funderburkjim** [comment]
I like the 'parallel' approach.  Have two independently generated corrections.  
Then I could generate comparisons of the two
and we'll iterate over the differences.  

@Andhrabharati  It's fine for you to work on AE as needed.  There is a lot of work to be done on the
non-verse portions,  so there is no current feeling of time pressure regarding the proofing.

**Comment by Andhrabharati** [comment]
OK, then let's go with my first proposal.

Will wait till Sampada finishes her round.

**Comment by Andhrabharati** [comment]
> there is no current feeling of time pressure regarding the proofing.

of course, there no time-pressure for any of the works here!!

**Comment by funderburkjim** [comment]
I prefer the 2nd proposal  --- each of you do it independently.  i.e., you don't need to wait for Sampada.

**Comment by Andhrabharati** [comment]
OK, then let it be so.

**Comment by funderburkjim** [comment]
## where to put the files?

Here's a suggestion of where to put the files for proofing.  
* Jim makes a repository funderburkjim/boesp-san-ab  (for Andhrabharati)
   * permission settings for Andhrabharati to push.
* Jim puts the initial version of the verses file into the repository
* Andhrabharati clones the repository.
* Andhrabharati modifies his local copy of file
   *  each day, after modifying local copy,  the local copy can be synced to Github.  
* When Andhrabharati done,  Jim can pull the revised file 

Similarly a repository funderburkjim/boesp-san-sampada  for Sampada's work.

This approach would have the advantages 
* No interference between the proofing work and other work being done in boesp-prep
   * This will make life easier by avoiding occasional tricky syncing obstacles
* Github tracking of versions, so no work can be lost
* Availability of Github issues, history, and other amenities.
* Similar process can be used with the verses from volumes 2 and 3 when they are available

Should we give this a try?

**Comment by Andhrabharati** [comment]
> each day, after modifying local copy, the local copy can be synced to Github.

Sorry, I don't like to do it this way; will be posting the full work once done with it.

**Comment by funderburkjim** [comment]
> will be posting the full work  

As you wish.

**Comment by funderburkjim** [comment]
@Andhrabharati   Have prepared repository https://github.com/funderburkjim/boesp-prep-ab for you.
The full devanagari verses are in file boesp-1_deva.txt .

Also invited you as 'a collaborator', which should give you full permissions on this repository.

Do you know how to clone this repository to your local computer?  
If you use GitBash, then the cloning command is
```
git clone https://github.com/funderburkjim/boesp-prep-ab.git
```

And when you want to commit your changes and push to Github
```
git add .
git commit -m "Brief description of reason for commit"
git push
```

**Comment by funderburkjim** [comment]
@sanskritisampada   Have prepared repository https://github.com/funderburkjim/boesp-prep-sam for you.
The verses from volume 1 are in file boesp-1_slp1.txt .

Also invited you as 'a collaborator', which should give you full permissions on this repository.

To clone this repository to your local computer with GitBash
```
git clone https://github.com/funderburkjim/boesp-prep-sam.git
```

And when you want to commit your changes and push to Github
```
git add .
git commit -m "Brief description of reason for commit"
git push
```

Since you are comfortable with Gitbash, suggest you commit your changes and push to Github after
most sessions (Vary the commit message to indicate the verses proofed in the session).

**Comment by funderburkjim** [comment]
## Comments in proofing file

You may want to make a comment occasionally in the proofing file.  If so, I request these comments
be inserted as lines beginning with the semicolon character ';'.  

Of course, if you have more elaborate comments, you can open an Issue in the repository.

## scan error

I don't think you need to be completely meticulous about noting cases where you suspect the printed text 
to be in error.  If you do want to record such print errors, then make a comment  starting with  the
phrase 'scan error'
e.g.
```
; scan error  : kulpa -> kalpa
```

**Comment by Andhrabharati** [comment]
> Do you know how to clone this repository to your local computer?

Just like to remind you that I am already using github platform, with Dhaval and CSL.

I do understand these processes well now.

**Comment by Andhrabharati** [comment]
> 
> Of course, if you have more elaborate comments, you can open an Issue in the repository.
> 

Posted several issues, as I looked into the file-

https://github.com/funderburkjim/boesp-prep-ab/issues/5#issue-988696637
https://github.com/funderburkjim/boesp-prep-ab/issues/4#issue-988685959
https://github.com/funderburkjim/boesp-prep-ab/issues/3#issue-988577200
https://github.com/funderburkjim/boesp-prep-ab/issues/2#issue-988562185
https://github.com/funderburkjim/boesp-prep-ab/issues/1#issue-988559285

**Comment by sanskritisampada** [comment]
Thanks Jim
This slp sample looks perfect for proofreading.
How do I proceed?

Sampada

**Comment by funderburkjim** [comment]
@Andhrabharati 

> I do understand these processes well now.

Got it!

**Comment by funderburkjim** [comment]
@sanskritisampada   

You proof read the verses, and make corrections as needed.

You probably will want to compare to the PDF  (see link above for getting pdf).

Also see instructions above.

You'll be doing all work in https://github.com/funderburkjim/boesp-prep-sam, as described above.
For further discussion, post in issues in boesp-prep-sam repository.

**Comment by funderburkjim** [comment]
Think this issue can be closed.
